### ISSUE TITLE
Freeze a Column from Sorting

### ISSUE THREAD

**Issue by rusrus** [joequery/Stupid-Table-Plugin#169] opened 2016-08-29 17:13 UTC
Hello, Was wondering if there was a way to freeze (or not sort) a column. I have a table with 3 columns and I want column 1 to remain entact and for the last 2 columns to have sorting ??

**Comment by rusrus** [comment] 2016-08-31 20:15
anyone ??

**Comment by svivian** [comment] 2016-09-01 00:12
Duplicate of #99

**Closed by svivian** 2016-09-01 00:12 UTC
